### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [michaelb108/colmaracademy#6]
Met expectations.

You match the view of the page.  Some of your errors are more due to a lack of experience.

Your html and css is well organized.

The main purpose of media queries is to change css to fit the page not to reveal a lot divs in mobile.  The navigation is different because we are removing one nav bar for a button base one.
The rest of the html media query just needs style changes.

I have two main concerns.

The first is that this point id shouldn't be used repeatedly, it really only should be used for scripting and in page linking.

Second the way you formatted your css.  It isn't part of the standard format and it makes it hard to find missing end points.  It wasn't easy to read.

**Comment by michaelb108** [comment]
Thanks for all your input! I made all the updates you recommended.
